### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by VictiniFan360** [CuerdOS/logo#1]
#### Propuesta: Nuevo Manual de Marca para CuerdOS

Hola equipo,

Quisiera proponer la creación de un nuevo manual de marca para CuerdOS. Considero que un manual de marca actualizado y detallado podría mejorar significativamente la coherencia visual y la percepción de nuestra distribución. Este manual incluiría:

- Logotipo y sus variantes (uso correcto e incorrecto).
- Paleta de colores oficial.
- Tipografía recomendada.

¿Qué opinan al respecto? ¿Creen que sería útil para nuestro proyecto? Me gustaría saber sus comentarios y sugerencias.

Saludos,  
Alejitao

---

#### Proposal: New Brand Manual for CuerdOS

Hi team,

I would like to propose the creation of a new brand manual for CuerdOS. I believe that an updated and detailed brand manual could significantly improve the visual consistency and perception of our distribution. This manual would include:

- Logo and its variations (correct and incorrect usage).
- Official color palette.
- Recommended typography.

What do you think about this? Do you believe it would be useful for our project? I would appreciate your feedback and suggestions.

Best regards,  
Alejitao
[Manual de marca CuerdOS.pdf](https://github.com/user-attachments/files/16762666/Manual.de.marca.CuerdOS.pdf)

**Comment by CuerdOS** [comment]
Hola Alejitao,

Nos ha parecido una propuesta bastante interesante y creo que tiene potencial con lo que respecta a la identidad de marca.

Le he echado un ojo al PDF y le he encontrado algunos detalles a mejorar:
 - La tipografía no es la indicada, la tipografía del logo de CuerdOS es Roboto Regular (excepto la parte de "OS", eso es Roboto Thin) con un tracking de 6,70 px.
 - Las variantes monocromáticas tienen una ligera distorsión del logo.
 
Te paso los SVG del logo con la tipografía original y la página de logos monocromáticos corregida:
![ByN cuerdos](https://github.com/user-attachments/assets/822d5740-4e99-4457-a5ab-9e3c2f628ef9)
![logo +  tipografia](https://github.com/user-attachments/assets/38a82e0c-aef9-42ef-a8fd-ca863c815b5a)

Gracias por el interés, ante cualquier duda puedes continuar este hilo o escribirnos a cuerdoslinux@proton.me.

Saludos cordiales :),
CuerdOS Dev Team.

**Comment by VictiniFan360** [comment]
Vale, he hecho las correcciones que me habéis pedido.
Aquí os las paso.
[Manual de marca CuerdOS.pdf](https://github.com/user-attachments/files/16781273/Manual.de.marca.CuerdOS.pdf)

**Comment by CuerdOS** [comment]
Hola Alejitao! Le hemos echado un vistazo al PDF y nos ha parecido bien para subirlo.
¿Podrías realizar un pull request al repositorio con el PDF? Para integrarlo al repositorio.

**Comment by VictiniFan360** [comment]
> Hola Alejitao! Le hemos echado un vistazo al PDF y nos ha parecido bien para subirlo. ¿Podrías realizar un pull request al repositorio con el PDF? Para integrarlo al repositorio.

¡Vale! Ya lo hago
